// <auto-generated />
using System;
using HomeDecorShop.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeDecorShop.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260324125007_AddProductAndCategorySeed")]
    partial class AddProductAndCategorySeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomeDecorShop.Domain.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("HomeDecorShop.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Phụ kiện bàn",
                            Slug = "phu-kien-ban"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Lighting",
                            Slug = "lighting"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Decor",
                            Slug = "decor"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Furniture",
                            Slug = "furniture"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Textile",
                            Slug = "textile"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Kitchen",
                            Slug = "kitchen"
                        });
                });

            modelBuilder.Entity("HomeDecorShop.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HoverImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OriginalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("Reviews")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoldPercentage")
                        .HasColumnType("int");

                    b.Property<int>("StockLeft")
                        .HasColumnType("int");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Brand = "BeeShop",
                            Category = "Phụ kiện bàn",
                            CategoryId = 1,
                            Color = "#8B4513",
                            CreatedAt = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoverImage = "https://picsum.photos/id/102/400/500",
                            Image = "https://picsum.photos/id/101/400/500",
                            InStock = true,
                            IsActive = true,
                            Material = "Gỗ",
                            Name = "Khay Cắm Bút Gỗ Sồi",
                            OriginalPrice = 180000m,
                            Price = 150000m,
                            Rating = 4.7999999999999998,
                            Reviews = 45,
                            Sku = "BEE-101",
                            Slug = "khay-cam-but-go-soi",
                            StockLeft = 0,
                            Style = "Minimalist",
                            Tag = "NEW"
                        },
                        new
                        {
                            Id = 102,
                            Brand = "BeeShop",
                            Category = "Lighting",
                            CategoryId = 2,
                            Color = "#333333",
                            CreatedAt = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoverImage = "https://picsum.photos/id/104/400/500",
                            Image = "https://picsum.photos/id/103/400/500",
                            InStock = true,
                            IsActive = true,
                            Material = "Kim loại",
                            Name = "Đèn Bàn Pixar",
                            Price = 350000m,
                            Rating = 4.9000000000000004,
                            Reviews = 120,
                            Sku = "BEE-102",
                            Slug = "den-ban-pixar",
                            StockLeft = 0,
                            Style = "Hiện đại",
                            Tag = "-20%"
                        },
                        new
                        {
                            Id = 103,
                            Brand = "BeeShop",
                            Category = "Phụ kiện bàn",
                            CategoryId = 1,
                            Color = "#D2B48C",
                            CreatedAt = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoverImage = "https://picsum.photos/id/107/400/500",
                            Image = "https://picsum.photos/id/106/400/500",
                            InStock = true,
                            IsActive = true,
                            Material = "Vải",
                            Name = "Bảng Ghim Ghi Chú",
                            Price = 120000m,
                            Rating = 4.5,
                            Reviews = 30,
                            Sku = "BEE-103",
                            Slug = "bang-ghim-ghi-chu",
                            StockLeft = 0,
                            Style = "Vintage"
                        },
                        new
                        {
                            Id = 104,
                            Brand = "BeeShop",
                            Category = "Decor",
                            CategoryId = 3,
                            Color = "#4CAF50",
                            CreatedAt = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoverImage = "https://picsum.photos/id/113/400/500",
                            Image = "https://picsum.photos/id/112/400/500",
                            InStock = true,
                            IsActive = true,
                            Material = "Gốm sứ",
                            Name = "Chậu Cây Mini Để Bàn",
                            Price = 85000m,
                            Rating = 5.0,
                            Reviews = 210,
                            Sku = "BEE-104",
                            Slug = "chau-cay-mini-de-ban",
                            StockLeft = 0,
                            Style = "Dễ thương",
                            Tag = "Best Seller"
                        },
                        new
                        {
                            Id = 105,
                            Brand = "BeeShop",
                            Category = "Phụ kiện bàn",
                            CategoryId = 1,
                            Color = "#8B4513",
                            CreatedAt = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoverImage = "https://picsum.photos/id/134/400/500",
                            Image = "https://picsum.photos/id/133/400/500",
                            InStock = true,
                            IsActive = true,
                            Material = "Gỗ",
                            Name = "Lịch Gỗ Để Bàn",
                            Price = 190000m,
                            Rating = 4.7000000000000002,
                            Reviews = 15,
                            Sku = "BEE-105",
                            Slug = "lich-go-de-ban",
                            StockLeft = 0,
                            Style = "Minimalist"
                        },
                        new
                        {
                            Id = 106,
                            Brand = "BeeShop",
                            Category = "Decor",
                            CategoryId = 3,
                            Color = "#FFFFFF",
                            CreatedAt = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoverImage = "https://picsum.photos/id/146/400/500",
                            Image = "https://picsum.photos/id/145/400/500",
                            InStock = true,
                            IsActive = true,
                            Material = "Gốm sứ",
                            Name = "Cốc Gốm Handmade",
                            OriginalPrice = 160000m,
                            Price = 145000m,
                            Rating = 4.5999999999999996,
                            Reviews = 55,
                            Sku = "BEE-106",
                            Slug = "coc-gom-handmade",
                            StockLeft = 0,
                            Style = "Vintage"
                        },
                        new
                        {
                            Id = 107,
                            Brand = "BeeShop",
                            Category = "Decor",
                            CategoryId = 3,
                            Color = "#333333",
                            CreatedAt = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoverImage = "https://picsum.photos/id/176/400/500",
                            Image = "https://picsum.photos/id/175/400/500",
                            InStock = true,
                            IsActive = true,
                            Material = "Nhựa",
                            Name = "Đồng Hồ Lật Số",
                            Price = 450000m,
                            Rating = 4.9000000000000004,
                            Reviews = 80,
                            Sku = "BEE-107",
                            Slug = "dong-ho-lat-so",
                            StockLeft = 0,
                            Style = "Hiện đại",
                            Tag = "Sold Out"
                        },
                        new
                        {
                            Id = 108,
                            Brand = "Nordic Nest",
                            Category = "Phụ kiện bàn",
                            CategoryId = 1,
                            Color = "#8B4513",
                            CreatedAt = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoverImage = "https://picsum.photos/id/161/400/500",
                            Image = "https://picsum.photos/id/160/400/500",
                            InStock = true,
                            IsActive = true,
                            Material = "Da",
                            Name = "Thảm Chuột Da",
                            Price = 220000m,
                            Rating = 4.7999999999999998,
                            Reviews = 90,
                            Sku = "BEE-108",
                            Slug = "tham-chuot-da",
                            StockLeft = 0,
                            Style = "Minimalist"
                        },
                        new
                        {
                            Id = 109,
                            Brand = "Moc Decor",
                            Category = "Kitchen",
                            CategoryId = 6,
                            Color = "#B08968",
                            CreatedAt = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoverImage = "https://picsum.photos/id/141/400/500",
                            Image = "https://picsum.photos/id/140/400/500",
                            InStock = true,
                            IsActive = true,
                            Material = "Gỗ",
                            Name = "Bộ Khay Gỗ Trang Trí Bàn Ăn",
                            OriginalPrice = 690000m,
                            Price = 520000m,
                            Rating = 4.5999999999999996,
                            Reviews = 66,
                            Sku = "BEE-109",
                            Slug = "bo-khay-go-trang-tri-ban-an",
                            StockLeft = 0,
                            Style = "Vintage"
                        },
                        new
                        {
                            Id = 110,
                            Brand = "LumiHome",
                            Category = "Lighting",
                            CategoryId = 2,
                            Color = "#222222",
                            CreatedAt = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoverImage = "https://picsum.photos/id/322/400/500",
                            Image = "https://picsum.photos/id/321/400/500",
                            InStock = true,
                            IsActive = true,
                            Material = "Kim loại",
                            Name = "Đèn Thả Trần Cafe Loft",
                            Price = 890000m,
                            Rating = 4.9000000000000004,
                            Reviews = 143,
                            Sku = "BEE-110",
                            Slug = "den-tha-tran-cafe-loft",
                            StockLeft = 0,
                            Style = "Hiện đại",
                            Tag = "Best Seller"
                        },
                        new
                        {
                            Id = 111,
                            Brand = "SoftNest",
                            Category = "Textile",
                            CategoryId = 5,
                            Color = "#E0A96D",
                            CreatedAt = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoverImage = "https://picsum.photos/id/326/400/500",
                            Image = "https://picsum.photos/id/325/400/500",
                            InStock = true,
                            IsActive = true,
                            Material = "Vải",
                            Name = "Gối Tựa Sofa Boho",
                            OriginalPrice = 240000m,
                            Price = 180000m,
                            Rating = 4.4000000000000004,
                            Reviews = 38,
                            Sku = "BEE-111",
                            Slug = "goi-tua-sofa-boho",
                            StockLeft = 0,
                            Style = "Dễ thương"
                        },
                        new
                        {
                            Id = 112,
                            Brand = "BeeLiving",
                            Category = "Decor",
                            CategoryId = 3,
                            Color = "#7F5539",
                            CreatedAt = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoverImage = "https://picsum.photos/id/331/400/500",
                            Image = "https://picsum.photos/id/330/400/500",
                            InStock = false,
                            IsActive = true,
                            Material = "Gỗ",
                            Name = "Kệ Gỗ Treo Tường Hex",
                            Price = 430000m,
                            Rating = 4.7000000000000002,
                            Reviews = 57,
                            Sku = "BEE-112",
                            Slug = "ke-go-treo-tuong-hex",
                            StockLeft = 0,
                            Style = "Minimalist"
                        },
                        new
                        {
                            Id = 113,
                            Brand = "SoftNest",
                            Category = "Textile",
                            CategoryId = 5,
                            Color = "#C9ADA7",
                            CreatedAt = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoverImage = "https://picsum.photos/id/339/400/500",
                            Image = "https://picsum.photos/id/338/400/500",
                            InStock = true,
                            IsActive = true,
                            Material = "Vải",
                            Name = "Thảm Lụa Trang Trí Phòng Ngủ",
                            OriginalPrice = 960000m,
                            Price = 760000m,
                            Rating = 4.9000000000000004,
                            Reviews = 102,
                            Sku = "BEE-113",
                            Slug = "tham-lua-trang-tri-phong-ngu",
                            StockLeft = 0,
                            Style = "Hiện đại"
                        },
                        new
                        {
                            Id = 114,
                            Brand = "Moc Decor",
                            Category = "Kitchen",
                            CategoryId = 6,
                            Color = "#A47148",
                            CreatedAt = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoverImage = "https://picsum.photos/id/345/400/500",
                            Image = "https://picsum.photos/id/344/400/500",
                            InStock = true,
                            IsActive = true,
                            Material = "Gỗ",
                            Name = "Set Thìa Nĩa Gỗ 6 Món",
                            Price = 250000m,
                            Rating = 4.2999999999999998,
                            Reviews = 22,
                            Sku = "BEE-114",
                            Slug = "set-thia-nia-go-6-mon",
                            StockLeft = 0,
                            Style = "Vintage"
                        },
                        new
                        {
                            Id = 115,
                            Brand = "LumiHome",
                            Category = "Lighting",
                            CategoryId = 2,
                            Color = "#2D2D2D",
                            CreatedAt = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoverImage = "https://picsum.photos/id/351/400/500",
                            Image = "https://picsum.photos/id/350/400/500",
                            InStock = true,
                            IsActive = true,
                            Material = "Gỗ",
                            Name = "Đèn Ngủ Gỗ Có Dimmer",
                            Price = 680000m,
                            Rating = 4.7999999999999998,
                            Reviews = 41,
                            Sku = "BEE-115",
                            Slug = "den-ngu-go-co-dimmer",
                            StockLeft = 0,
                            Style = "Minimalist",
                            Tag = "NEW"
                        },
                        new
                        {
                            Id = 116,
                            Brand = "Nordic Nest",
                            Category = "Furniture",
                            CategoryId = 4,
                            Color = "#8D6E63",
                            CreatedAt = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoverImage = "https://picsum.photos/id/356/400/500",
                            Image = "https://picsum.photos/id/355/400/500",
                            InStock = true,
                            IsActive = true,
                            Material = "Gỗ",
                            Name = "Tủ Đầu Giường 2 Ngăn Kéo",
                            Price = 1490000m,
                            Rating = 4.5999999999999996,
                            Reviews = 29,
                            Sku = "BEE-116",
                            Slug = "tu-dau-giuong-2-ngan-keo",
                            StockLeft = 0,
                            Style = "Hiện đại"
                        },
                        new
                        {
                            Id = 117,
                            Brand = "BeeLiving",
                            Category = "Kitchen",
                            CategoryId = 6,
                            Color = "#EDE0D4",
                            CreatedAt = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoverImage = "https://picsum.photos/id/362/400/500",
                            Image = "https://picsum.photos/id/361/400/500",
                            InStock = false,
                            IsActive = true,
                            Material = "Vải",
                            Name = "Khăn Trải Bàn Linen Kem",
                            OriginalPrice = 390000m,
                            Price = 310000m,
                            Rating = 4.5,
                            Reviews = 36,
                            Sku = "BEE-117",
                            Slug = "khan-trai-ban-linen-kem",
                            StockLeft = 0,
                            Style = "Minimalist"
                        },
                        new
                        {
                            Id = 118,
                            Brand = "Artify",
                            Category = "Decor",
                            CategoryId = 3,
                            Color = "#B0A8B9",
                            CreatedAt = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoverImage = "https://picsum.photos/id/369/400/500",
                            Image = "https://picsum.photos/id/368/400/500",
                            InStock = true,
                            IsActive = true,
                            Material = "Canvas",
                            Name = "Bộ 3 Khung Tranh Trừu Tượng",
                            Price = 580000m,
                            Rating = 4.7000000000000002,
                            Reviews = 73,
                            Sku = "BEE-118",
                            Slug = "bo-3-khung-tranh-truu-tuong",
                            StockLeft = 0,
                            Style = "Hiện đại"
                        },
                        new
                        {
                            Id = 119,
                            Brand = "AromaBee",
                            Category = "Decor",
                            CategoryId = 3,
                            Color = "#FFF4D6",
                            CreatedAt = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoverImage = "https://picsum.photos/id/376/400/500",
                            Image = "https://picsum.photos/id/375/400/500",
                            InStock = true,
                            IsActive = true,
                            Material = "Sáp đậu nành",
                            Name = "Nến Thơm Vani Hũ Thủy Tinh",
                            OriginalPrice = 210000m,
                            Price = 165000m,
                            Rating = 4.2000000000000002,
                            Reviews = 64,
                            Sku = "BEE-119",
                            Slug = "nen-thom-vani-hu-thuy-tinh",
                            StockLeft = 0,
                            Style = "Dễ thương"
                        },
                        new
                        {
                            Id = 120,
                            Brand = "Artify",
                            Category = "Decor",
                            CategoryId = 3,
                            Color = "#2A9D8F",
                            CreatedAt = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoverImage = "https://picsum.photos/id/382/400/500",
                            Image = "https://picsum.photos/id/381/400/500",
                            InStock = true,
                            IsActive = true,
                            Material = "Thủy tinh",
                            Name = "Bình Hoa Thủy Tinh Xanh Rêu",
                            Price = 410000m,
                            Rating = 4.7999999999999998,
                            Reviews = 88,
                            Sku = "BEE-120",
                            Slug = "binh-hoa-thuy-tinh-xanh-rieu",
                            StockLeft = 0,
                            Style = "Vintage"
                        },
                        new
                        {
                            Id = 121,
                            Brand = "Nordic Nest",
                            Category = "Furniture",
                            CategoryId = 4,
                            Color = "#6D597A",
                            CreatedAt = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoverImage = "https://picsum.photos/id/389/400/500",
                            Image = "https://picsum.photos/id/388/400/500",
                            InStock = true,
                            IsActive = true,
                            Material = "Vải",
                            Name = "Ghế Đôn Bọc Vải Nhung",
                            Price = 980000m,
                            Rating = 4.5,
                            Reviews = 27,
                            Sku = "BEE-121",
                            Slug = "ghe-don-boc-vai-nhung",
                            StockLeft = 0,
                            Style = "Vintage"
                        },
                        new
                        {
                            Id = 122,
                            Brand = "Moc Decor",
                            Category = "Kitchen",
                            CategoryId = 6,
                            Color = "#F4EBD0",
                            CreatedAt = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoverImage = "https://picsum.photos/id/395/400/500",
                            Image = "https://picsum.photos/id/394/400/500",
                            InStock = true,
                            IsActive = true,
                            Material = "Thủy tinh",
                            Name = "Bộ Ly Thủy Tinh Viền Vàng",
                            OriginalPrice = 520000m,
                            Price = 460000m,
                            Rating = 4.9000000000000004,
                            Reviews = 112,
                            Sku = "BEE-122",
                            Slug = "bo-ly-thuy-tinh-co-vien-vang",
                            StockLeft = 0,
                            Style = "Hiện đại"
                        },
                        new
                        {
                            Id = 123,
                            Brand = "BeeLiving",
                            Category = "Decor",
                            CategoryId = 3,
                            Color = "#D6CCC2",
                            CreatedAt = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoverImage = "https://picsum.photos/id/402/400/500",
                            Image = "https://picsum.photos/id/401/400/500",
                            InStock = true,
                            IsActive = true,
                            Material = "Gỗ",
                            Name = "Gương Tròn Viền Gỗ Sồi",
                            Price = 1250000m,
                            Rating = 4.7000000000000002,
                            Reviews = 46,
                            Sku = "BEE-123",
                            Slug = "guong-tron-vien-go-soi",
                            StockLeft = 0,
                            Style = "Minimalist"
                        },
                        new
                        {
                            Id = 124,
                            Brand = "AromaBee",
                            Category = "Kitchen",
                            CategoryId = 6,
                            Color = "#E3D5CA",
                            CreatedAt = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            HoverImage = "https://picsum.photos/id/410/400/500",
                            Image = "https://picsum.photos/id/409/400/500",
                            InStock = false,
                            IsActive = true,
                            Material = "Gốm sứ",
                            Name = "Set Khay Gốm Breakfast",
                            Price = 340000m,
                            Rating = 4.2999999999999998,
                            Reviews = 18,
                            Sku = "BEE-124",
                            Slug = "set-khay-gom-breakfast",
                            StockLeft = 0,
                            Style = "Dễ thương"
                        });
                });

            modelBuilder.Entity("HomeDecorShop.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HomeDecorShop.Domain.Address", b =>
                {
                    b.HasOne("HomeDecorShop.Domain.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeDecorShop.Domain.Product", b =>
                {
                    b.HasOne("HomeDecorShop.Domain.Category", "CategoryNavigation")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryNavigation");
                });

            modelBuilder.Entity("HomeDecorShop.Domain.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("HomeDecorShop.Domain.User", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
