using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HomeDecorShop.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class SeedProductsPart2 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Products Seed Part 2 - 1-to-1 Mapping Continued (Alphabetical)
            migrationBuilder.InsertData(
                table: "Products",
                columns: new[] { "ProductId", "Brand", "Category", "CategoryId", "Color", "CreatedAt", "Description", "HoverImage", "Image", "InStock", "IsActive", "Material", "OldPrice", "Price", "ProductName", "Rating", "Reviews", "Sku", "Slug", "SoldPercentage", "StockLeft", "Style", "Tag", "VideoUrl" },
                values: new object[,] {
                    { 51, "BeeShop", "Trang trí", 11, "Gỗ", DateTime.UtcNow, "Khung ảnh gỗ đơn giản, sang trọng.", "assets/images/khung-anh-go.jpg", "assets/images/khung-anh-go.jpg", true, true, "Gỗ", null, 75000m, "KHUNG ẢNH GỖ", 4.5, 10, "BEE-051", "khung-ảnh-gỗ", 0, 50, "Minimal", "NEW", null },
                    { 52, "BeeShop", "Trang trí", 11, "Trắng", DateTime.UtcNow, "Khung ảnh mini để bàn cực xinh.", "assets/images/khung-mini.jpg", "assets/images/khung-mini.jpg", true, true, "Gỗ/Nhựa", null, 45000m, "KHUNG MINI ĐỂ BÀN", 4.5, 10, "BEE-052", "khung-mini-để-bàn", 0, 50, "Cute", "NEW", null },
                    { 53, "BeeShop", "Trang trí", 11, "Nâu nhám", DateTime.UtcNow, "Lọ gốm bề mặt nhám phong cách hiện đại.", "assets/images/lo-gom-nham.jpg", "assets/images/lo-gom-nham.jpg", true, true, "Gốm", null, 110000m, "LỌ HOA GỐM NHÁM", 4.5, 10, "BEE-053", "lọ-hoa-gốm-nhám", 0, 50, "Modern", "NEW", null },
                    { 54, "BeeShop", "Trang trí", 11, "Trong suốt", DateTime.UtcNow, "Lọ hoa thủy tinh trong suốt tinh tế.", "assets/images/lo-hoa-thuy-tinh.jpg", "assets/images/lo-hoa-thuy-tinh.jpg", true, true, "Thủy tinh", null, 90000m, "LỌ THỦY TINH TRONG", 4.5, 10, "BEE-054", "lọ-thủy-tinh-trong", 0, 50, "Minimal", "NEW", null },
                    { 55, "BeeShop", "Trang trí", 11, "Trắng hồng", DateTime.UtcNow, "Lọ hoa dáng tròn mềm mại.", "assets/images/lo-hoa-tron.jpg", "assets/images/lo-hoa-tron.jpg", true, true, "Gốm sứ", null, 130000m, "LỌ HOA DÁNG TRÒN", 4.5, 10, "BEE-055", "lọ-hoa-dáng-tròn", 0, 50, "Pastel", "NEW", null },
                    { 56, "BeeShop", "Trang trí", 11, "Pastel", DateTime.UtcNow, "Lọ hoa thủy tinh màu pastel độc đáo.", "assets/images/lo-mau.jpg", "assets/images/lo-mau.jpg", true, true, "Thủy tinh", null, 150000m, "LỌ HOA MÀU", 4.5, 10, "BEE-056", "lọ-hoa-màu", 0, 50, "Modern", "NEW", null },
                    { 57, "BeeShop", "Trang trí", 11, "Trắng kem", DateTime.UtcNow, "Lọ hoa men trắng cao cấp từ Bát Tràng.", "assets/images/lo-men-trang.jpg", "assets/images/lo-men-trang.jpg", true, true, "Gốm sứ", null, 180000m, "LỌ HOA MEN TRẮNG", 4.5, 10, "BEE-057", "lọ-hoa-men-trắng", 0, 50, "Traditional", "NEW", null },
                    { 58, "BeeShop", "Cốc ly", 2, "Họa tiết", DateTime.UtcNow, "Ly gốm bé dùng cho trà đạo hoặc cafe espresso.", "assets/images/ly-gom-be.jpg", "assets/images/ly-gom-be.jpg", true, true, "Gốm", null, 45000m, "LY GỐM NHỎ", 4.5, 10, "BEE-058", "ly-gốm-nhỏ", 0, 50, "Zen", "NEW", null },
                    { 59, "BeeShop", "Cốc ly", 2, "Họa tiết", DateTime.UtcNow, "Ly sứ với họa tiết vẽ tay độc đáo.", "assets/images/ly-hoa-tiet.jpg", "assets/images/ly-hoa-tiet.jpg", true, true, "Sứ", null, 75000m, "LY SỨ HỌA TIẾT", 4.5, 10, "BEE-059", "ly-sứ-họa-tiết", 0, 50, "Traditional", "NEW", null },
                    { 60, "BeeShop", "Cốc ly", 2, "Trắng", DateTime.UtcNow, "Ly sứ phong cách tối giản cho văn phòng.", "assets/images/ly-minimal.jpg", "assets/images/ly-minimal.jpg", true, true, "Sứ", null, 60000m, "LY SỨ MINIMAL", 4.5, 10, "BEE-060", "ly-sứ-minimal", 0, 50, "Minimal", "NEW", null },
                    { 61, "BeeShop", "Cốc ly", 2, "Nâu", DateTime.UtcNow, "Ly gốm có tay cầm chắc chắn, giữ nhiệt tốt.", "assets/images/ly-tay-cam.jpg", "assets/images/ly-tay-cam.jpg", true, true, "Gốm", null, 90000m, "LY GỐM TAY CẦM", 4.5, 10, "BEE-061", "ly-gốm-tay-cầm", 0, 50, "Rustic", "NEW", null },
                    { 62, "BeeShop", "Cốc ly", 2, "Trắng bóng", DateTime.UtcNow, "Ly sứ trắng tinh khôi, dễ dàng in logo hoặc trang trí.", "assets/images/ly-trang.jpg", "assets/images/ly-trang.jpg", true, true, "Sứ", null, 50000m, "LY SỨ TRẮNG", 4.5, 10, "BEE-062", "ly-sứ-trắng", 0, 50, "Pure", "NEW", null },
                    { 63, "BeeShop", "Trang trí", 11, "Trắng", DateTime.UtcNow, "Vật dụng trang trí Macrame dệt tay tỉ mỉ.", "assets/images/macrame.jpg", "assets/images/macrame.jpg", true, true, "Sợi Cotton", null, 180000m, "MACRAME DECOR", 4.5, 10, "BEE-063", "macrame-decor", 0, 50, "Boho", "NEW", null },
                    { 64, "BeeShop", "Trang trí", 11, "Trắng", DateTime.UtcNow, "Trang trí ban công với Macrame cao cấp.", "assets/images/macrame-ban-cong.jpg", "assets/images/macrame-ban-cong.jpg", true, true, "Sợi Cotton", null, 220000m, "MACRAME BAN CÔNG", 4.5, 10, "BEE-064", "macrame-ban-công", 0, 50, "Outdoor", "NEW", null },
                    { 65, "BeeShop", "Trang trí", 11, "Trắng", DateTime.UtcNow, "Rèm cửa Macrame cho không gian thêm lãng mạn.", "assets/images/macrame-cua.jpg", "assets/images/macrame-cua.jpg", true, true, "Sợi Cotton", null, 350000m, "RÈM MACRAME", 4.5, 10, "BEE-065", "rèm-macrame", 0, 50, "Vintage", "NEW", null },
                    { 66, "BeeShop", "Trang trí", 11, "Trắng ngà", DateTime.UtcNow, "Kệ Macrame treo tường để đồ trang trí nhẹ.", "assets/images/macrame-ke.jpg", "assets/images/macrame-ke.jpg", true, true, "Sợi + Gỗ", null, 280000m, "KỆ TREO MACRAME", 4.5, 10, "BEE-066", "kệ-treo-macrame", 0, 50, "Boho", "NEW", null },
                    { 67, "BeeShop", "Trang trí", 11, "Trắng", DateTime.UtcNow, "Macrame mini treo xe hơi hoặc trang trí nhỏ.", "assets/images/macrame-mini.jpg", "assets/images/macrame-mini.jpg", true, true, "Sợi Cotton", null, 65000m, "MACRAME MINI", 4.5, 10, "BEE-067", "macrame-mini", 0, 50, "Cute", "NEW", null },
                    { 68, "BeeShop", "Hương thơm", 3, "Vàng chanh", DateTime.UtcNow, "Nến thơm hương chanh sả khử mùi hiệu quả.", "assets/images/nen-chanh-sa.jpg", "assets/images/nen-chanh-sa.jpg", true, true, "Sáp thực vật", null, 95000m, "NẾN CHANH SẢ", 4.5, 10, "BEE-068", "nến-chanh-sả", 0, 50, "Fresh", "NEW", null },
                    { 69, "BeeShop", "Hương thơm", 3, "Đỏ dâu", DateTime.UtcNow, "Nến thơm hương dâu tây ngọt ngào.", "assets/images/nen-dau.jpg", "assets/images/nen-dau.jpg", true, true, "Sáp thực vật", null, 95000m, "NẾN DÂU TÂY", 4.5, 10, "BEE-069", "nến-dâu-tây", 0, 50, "Sweet", "NEW", null },
                    { 70, "BeeShop", "Hương thơm", 3, "Nhiều màu", DateTime.UtcNow, "Cốc nến thủy tinh trang trí đa mục đích.", "assets/images/nen-lo.jpg", "assets/images/nen-lo.jpg", true, true, "Thủy tinh + Sáp", null, 11000m, "NẾN CỐC THỦY TINH", 4.5, 10, "BEE-070", "nến-cốc-thủy-tinh", 0, 50, "Pure", "NEW", null },
                    { 71, "BeeShop", "Hương thơm", 3, "Xanh matcha", DateTime.UtcNow, "Nến thơm hương Matcha thanh khiết, thư giãn.", "assets/images/nen-matcha.jpg", "assets/images/nen-matcha.jpg", true, true, "Sáp thực vật", null, 95000m, "NẾN THƠM MATCHA", 4.5, 10, "BEE-071", "nến-thơm-matcha", 0, 50, "Japan", "NEW", null },
                    { 72, "BeeShop", "Hương thơm", 3, "Trắng nhài", DateTime.UtcNow, "Nến thơm hương hoa nhài dịu nhẹ.", "assets/images/nen-nhai.jpg", "assets/images/nen-nhai.jpg", true, true, "Sáp thực vật", null, 95000m, "NẾN HOA NHÀI", 4.5, 10, "BEE-072", "nến-hoa-nhài", 0, 50, "Elegant", "NEW", null },
                    { 73, "BeeShop", "Hương thơm", 3, "Tím", DateTime.UtcNow, "Nến thơm Lavender mang lại giấc ngủ ngon.", "assets/images/nen-thom-lavender-relax.jpg", "assets/images/nen-thom-lavender-relax.jpg", true, true, "Sáp thực vật", null, 120000m, "NẾN LAVENDER RELAX", 4.5, 10, "BEE-073", "nến-lavender-relax", 0, 50, "Relax", "NEW", null },
                    { 74, "BeeShop", "Hương thơm", 3, "Vàng kem", DateTime.UtcNow, "Nến thơm hương Vanilla ngọt lịm ấm áp.", "assets/images/nen-vanilla.jpg", "assets/images/nen-vanilla.jpg", true, true, "Sáp thực vật", null, 95000m, "NẾN VANILLA WARM", 4.5, 10, "BEE-074", "nến-vanilla-warm", 0, 50, "Sweet", "NEW", null },
                    { 75, "BeeShop", "Đồ trang điểm", 15, "Xanh bạc hà", DateTime.UtcNow, "Son dưỡng môi hương bạc hà mát lạnh.", "assets/images/son-bac-ha.jpg", "assets/images/son-bac-ha.jpg", true, true, "Tự nhiên", null, 55000m, "SON DƯỠNG BẠC HÀ", 4.5, 10, "BEE-075", "son-dưỡng-bạc-hà", 0, 50, "Fresh", "NEW", null },
                    { 76, "BeeShop", "Đồ trang điểm", 15, "Cam đào", DateTime.UtcNow, "Son dưỡng môi chiết xuất hương cam tươi.", "assets/images/son-cam.jpg", "assets/images/son-cam.jpg", true, true, "Tự nhiên", null, 55000m, "SON DƯỠNG CAM", 4.5, 10, "BEE-076", "son-dưỡng-cam", 0, 50, "Fruit", "NEW", null },
                    { 77, "BeeShop", "Đồ trang điểm", 15, "Dừa", DateTime.UtcNow, "Son dưỡng môi dầu dừa nguyên chất dưỡng ẩm sâu.", "assets/images/son-dua.jpg", "assets/images/son-dua.jpg", true, true, "Dầu dừa", null, 60000m, "SON DƯỠNG DẦU DỪA", 4.5, 10, "BEE-077", "son-dưỡng-dầu-dừa", 0, 50, "Organic", "NEW", null },
                    { 78, "BeeShop", "Đồ trang điểm", 15, "Tự nhiên", DateTime.UtcNow, "Son dưỡng không màu, an toàn tuyệt đối.", "assets/images/son-duong.jpg", "assets/images/son-duong.jpg", true, true, "Sáp ong", null, 50000m, "SON DƯỠNG TỰ NHIÊN", 4.5, 10, "BEE-078", "son-dưỡng-tự-nhiên", 0, 50, "Pure", "NEW", null },
                    { 79, "BeeShop", "Đồ trang điểm", 15, "Hồng cánh sen", DateTime.UtcNow, "Son dưỡng môi hương hoa hồng dịu nhẹ.", "assets/images/son-hong.jpg", "assets/images/son-hong.jpg", true, true, "Tự nhiên", null, 55000m, "SON DƯỠNG HOA HỒNG", 4.5, 10, "BEE-079", "son-dưỡng-hoa-hồng", 0, 50, "Floral", "NEW", null },
                    { 80, "BeeShop", "Đồ trang điểm", 15, "Trong", DateTime.UtcNow, "Thành phần 100% tự nhiên không gây thâm môi.", "assets/images/son-tu-nhien.jpg", "assets/images/son-tu-nhien.jpg", true, true, "Thiên nhiên", null, 65000m, "SON ORGANIC", 4.5, 10, "BEE-080", "son-organic", 0, 50, "Natural", "NEW", null },
                    { 81, "BeeShop", "Phụ kiện vải", 8, "Họa tiết", DateTime.UtcNow, "Khăn Runner bàn ăn phong cách hiện đại.", "assets/images/table-runner.jpg", "assets/images/table-runner.jpg", true, true, "Vải dệt", null, 11000m, "KHĂN TABLE RUNNER", 4.5, 10, "BEE-081", "khăn-table-runner", 0, 50, "Modern", "NEW", null },
                    { 82, "BeeShop", "Phụ kiện vải", 8, "Trắng ngà", DateTime.UtcNow, "Thảm lông mềm mịn cho phòng ngủ thêm sang trọng.", "assets/images/tham-long.jpg", "assets/images/tham-long.jpg", true, true, "Lông nhân tạo", null, 250000m, "THẢM LÔNG CAO CẤP", 4.5, 10, "BEE-082", "thảm-lông-cao-cấp", 0, 50, "Luxury", "NEW", null },
                    { 83, "BeeShop", "Phụ kiện vải", 8, "Nhiều màu", DateTime.UtcNow, "Thảm trải sàn mini phong cách trẻ trung.", "assets/images/tham-mini.jpg", "assets/images/tham-mini.jpg", true, true, "Sợi cotton", null, 120000m, "THẢM TRẢI MINI", 4.5, 10, "BEE-083", "thảm-trải-mini", 0, 50, "Cozy", "NEW", null },
                    { 84, "BeeShop", "Phụ kiện vải", 8, "Đa sắc", DateTime.UtcNow, "Thảm tròn decor đẹp mắt cho phòng khách.", "assets/images/tham-tron.jpg", "assets/images/tham-tron.jpg", true, true, "Vải bện", null, 180000m, "THẢM TRÒN DECOR", 4.5, 10, "BEE-084", "thảm-tròn-decor", 0, 50, "Artistic", "NEW", null },
                    { 85, "BeeShop", "Hương thơm", 3, "Vàng", DateTime.UtcNow, "Tinh dầu thiên nhiên nguyên chất.", "assets/images/tinh-dau.jpg", "assets/images/tinh-dau.jpg", true, true, "Tinh dầu", null, 75000m, "TINH DẦU NGUYÊN CHẤT", 4.5, 10, "BEE-085", "tinh-dầu-nguyên-chất", 0, 50, "Natural", "NEW", null },
                    { 86, "BeeShop", "Hương thơm", 3, "Xanh", DateTime.UtcNow, "Tinh dầu bạc hà nguyên chất, sảng khoái.", "assets/images/tinh-dau-bac-ha.jpg", "assets/images/tinh-dau-bac-ha.jpg", true, true, "Tinh dầu", null, 80000m, "TINH DẦU BẠC HÀ", 4.5, 10, "BEE-086", "tinh-dầu-bạc-hà", 0, 50, "Fresh", "NEW", null },
                    { 87, "BeeShop", "Hương thơm", 3, "Vàng", DateTime.UtcNow, "Tinh dầu chanh tươi mát, khử mùi tốt.", "assets/images/tinh-dau-chanh.jpg", "assets/images/tinh-dau-chanh.jpg", true, true, "Tinh dầu", null, 80000m, "TINH DẦU CHANH", 4.5, 10, "BEE-087", "tinh-dầu-chanh", 0, 50, "Clean", "NEW", null },
                    { 88, "BeeShop", "Hương thơm", 3, "Đỏ hồng", DateTime.UtcNow, "Tinh dầu hoa hồng lãng mạn, quyến rũ.", "assets/images/tinh-dau-hoa-hong.jpg", "assets/images/tinh-dau-hoa-hong.jpg", true, true, "Tinh dầu", null, 90000m, "TINH DẦU HOA HỒNG", 4.5, 10, "BEE-088", "tinh-dầu-hoa-hồng", 0, 50, "Romantic", "NEW", null },
                    { 89, "BeeShop", "Hương thơm", 3, "Tím", DateTime.UtcNow, "Tinh dầu oải hương giúp giảm stress.", "assets/images/tinh-dau-lavender.jpg", "assets/images/tinh-dau-lavender.jpg", true, true, "Tinh dầu", null, 90000m, "TINH DẦU LAVENDER", 4.5, 10, "BEE-089", "tinh-dầu-lavender", 0, 50, "Relax", "NEW", null },
                    { 90, "BeeShop", "Hương thơm", 3, "Trong", DateTime.UtcNow, "Tinh dầu tràm hiệu quả trong việc phòng cảm.", "assets/images/tinh-dau-tram.jpg", "assets/images/tinh-dau-tram.jpg", true, true, "Tinh dầu", null, 85000m, "TINH DẦU TRÀM", 4.5, 10, "BEE-090", "tinh-dầu-tràm", 0, 50, "Health", "NEW", null },
                    { 91, "BeeShop", "Trang trí tường", 12, "Đa sắc", DateTime.UtcNow, "Tranh trừu tượng nghệ thuật hiện đại.", "assets/images/tranh-abstract.jpg", "assets/images/tranh-abstract.jpg", true, true, "Canvas", null, 200000m, "TRANH ABSTRACT", 4.5, 10, "BEE-091", "tranh-abstract", 0, 50, "Modern", "NEW", null },
                    { 92, "BeeShop", "Trang trí tường", 12, "Tối giản", DateTime.UtcNow, "Tranh Canvas tối giản cho văn phòng.", "assets/images/tranh-canvas-minimal.jpg", "assets/images/tranh-canvas-minimal.jpg", true, true, "Canvas", null, 150000m, "TRANH MINIMALIST", 4.5, 10, "BEE-092", "tranh-minimalist", 0, 50, "Minimal", "NEW", null },
                    { 93, "BeeShop", "Trang trí tường", 12, "Cổ điển", DateTime.UtcNow, "Tranh chủ đề cửa sổ tâm hồn.", "assets/images/tranh-cua.jpg", "assets/images/tranh-cua.jpg", true, true, "Canvas", null, 180000m, "TRANH CỬA SỔ", 4.5, 10, "BEE-093", "tranh-cửa-sổ", 0, 50, "Vintage", "NEW", null },
                    { 94, "BeeShop", "Trang trí tường", 12, "Floral", DateTime.UtcNow, "Tranh hoa lá rực rỡ sắc màu.", "assets/images/tranh-hoa-la.jpg", "assets/images/tranh-hoa-la.jpg", true, true, "Canvas", null, 180000m, "TRANH HOA LÁ", 4.5, 10, "BEE-094", "tranh-hoa-lá", 0, 50, "Nature", "NEW", null },
                    { 95, "BeeShop", "Trang trí tường", 12, "Đen trắng", DateTime.UtcNow, "Tranh vẽ đường nét tinh tế.", "assets/images/tranh-lineart.jpg", "assets/images/tranh-lineart.jpg", true, true, "Canvas", null, 140000m, "TRANH LINE ART", 4.5, 10, "BEE-095", "tranh-line-art", 0, 50, "Minimal", "NEW", null },
                    { 96, "BeeShop", "Trang trí tường", 12, "Tự nhiên", DateTime.UtcNow, "Tranh phong cảnh hùng vĩ.", "assets/images/tranh-phong-canh.jpg", "assets/images/tranh-phong-canh.jpg", true, true, "Canvas", null, 250000m, "TRANH PHONG CẢNH", 4.5, 10, "BEE-096", "tranh-phong-cảnh", 0, 50, "Classic", "NEW", null },
                    { 97, "BeeShop", "Trang trí tường", 12, "Cozy", DateTime.UtcNow, "Tranh trang trí phòng ngủ ấm cúng.", "assets/images/tranh-phong-ngu.jpg", "assets/images/tranh-phong-ngu.jpg", true, true, "Canvas", null, 210000m, "TRANH PHÒNG NGỦ", 4.5, 10, "BEE-097", "tranh-phòng-ngủ", 0, 50, "Modern", "NEW", null },
                    { 98, "BeeShop", "Trang trí tường", 12, "Typo", DateTime.UtcNow, "Tranh chữ truyền động lực.", "assets/images/tranh-typo.jpg", "assets/images/tranh-typo.jpg", true, true, "Canvas", null, 130000m, "TRANH TYPOGRAPHY", 4.5, 10, "BEE-098", "tranh-typography", 0, 50, "Modern", "NEW", null },
                    { 99, "BeeShop", "Trang trí", 11, "Vàng/Đen", DateTime.UtcNow, "Tượng điêu khắc nghệ thuật trưng kệ sách.", "assets/images/tuong-decor.jpg", "assets/images/tuong-decor.jpg", true, true, "Composite", null, 320000m, "TƯỢNG ART DECOR", 4.5, 10, "BEE-099", "tượng-art-decor", 0, 50, "Luxury", "NEW", null },
                    { 100, "BeeShop", "Trang trí", 11, "Xám", DateTime.UtcNow, "Tượng mini để bàn làm việc.", "assets/images/tuong-mini.jpg", "assets/images/tuong-mini.jpg", true, true, "Thạch cao", null, 80000m, "TƯỢNG MINI PHI HÀNH GIA", 4.5, 10, "BEE-100", "tượng-mini-phi-hành-gia", 0, 50, "Inspiration", "NEW", null },
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DELETE FROM Products WHERE ProductId > 50 AND ProductId <= 100");
        }
    }
}
